eTicket/Models/Actor.cs
using eTicket.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace eTicket.Models
{
    public class Actor : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        
        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePictureURL { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength =3,ErrorMessage ="Name should be between 3 to 50 chars")]
        public string FullName { get; set;}

        [Display(Name = "Bio")]
        [Required(ErrorMessage = "Bio is required")]
        public string Bio { get; set;}


        //Relationships
        public List<Actor_Movie> Actors_Movies { get; set; }
    }
}

eTicket/Controllers/ActorsController.cs
using eTicket.Data;
using eTicket.Data.Services;
using eTicket.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTicket.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorService _service;
        public ActorsController(IActorService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allActors = await _service.getAllAsync();
            return View(allActors);
        }
        // Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            ModelState.Remove("Actors_Movies");
            if (ModelState.IsValid)
            {
                await _service.AddAsync(actor);
                return RedirectToAction(nameof(Index));
            }

            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(actor);
        }

        // Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Not Found");
            return View(actorDetails);

        }

        // Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Not Found");
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            ModelState.Remove("Actors_Movies");
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(id, actor);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Not Found");
            return View(actorDetails);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Not Found");
            
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTicket/Controllers/MoviesController.cs
using eTicket.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTicket.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;
        public MoviesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allMovies = await _context.Movies.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            return View(allMovies);
        }
    }
}

eTicket/Views/Actors/Create.cshtml
@model Actor

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div calss="col-md-10 offset-2">
        <p>
            <h1>Add a new actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center" style="margin: 10px 0 10px 0">
                        <img class="rounded-circle" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>

                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

eTicket/Views/Actors/Delete.cshtml
@model Actor

@{
    ViewData["Title"] ="Delete"+@Model.FullName;
}

<div class="row text">
    <div calss="col-md-10 offset-2">
        <p>
            <h1>Delete Confirmation for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                    <div class="form-group text-center" style="margin: 10px 0 10px 0">
                        <img class="rounded-circle" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>

                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    
                    <div class="form-group" style="margin: 10px 0 10px 0">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-end" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

    </script>
}

eTicket/Views/Actors/Details.cshtml
@model Actor

@{
    ViewData["Title"] = @Model.FullName;
}

<div class="row text">
    <div calss="col-md-10 offset-2">
        <p>
            <h1>Details for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                    <div class="form-group text-center" style="margin: 10px 0 10px 0">
                        <img class="rounded-circle" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>

                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <a class="btn btn-success float-end" asp-action="Edit" asp-route-id="@Model.Id">Edit </a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

    </script>
}

eTicket/Views/Actors/Edit.cshtml
@model Actor

@{
    ViewData["Title"] = "Update actor";
}

<div class="row text">
    <div calss="col-md-10 offset-2">
        <p>
            <h1>Update actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center" style="margin: 10px 0 10px 0">
                        <img class="rounded-circle" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>

                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group" style="margin: 10px 0 10px 0">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

eTicket/Views/Actors/Index.cshtml
@model IEnumerable<Actor>

@{
    ViewData["Title"] = "List of Actors";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="text-center">
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-controller="Actors" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-info text-white" asp-controller="Actors" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-controller="Actors" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<div class="text-white" style="position:fixed; right: 25px; bottom: 50px;">
    <a asp-controller="Actors" asp-action="Create" class="btn btn-success"><i class="bg-info bi-plus-circle"></i> Add New </a>
</div>

eTicket/Views/Actors/Not Found.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="Text-info">Yous've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>